from enum import Enum


class AggregationLevel(str, Enum):
    RAW = "raw"
    FIFTEEN_MIN = "15min"
    THIRTY_MIN = "30min"
    HOURLY = "1h"
    FOUR_HOUR = "4h"
    DAILY = "1d"


class DartsModelId(str, Enum):
    # Scorers
    KMEANS = "kmeans"
    ISOLATION_FOREST = "isolation_forest"
    LOF = "lof"
    ECOD = "ecod"
    WASSERSTEIN = "wasserstein"
    COPOD = "copod"
    HBOS = "hbos"
    KNN = "knn"
    OCSVM = "ocsvm"
    INNE = "inne"
    LODA = "loda"
    CBLOF = "cblof"
    ROD = "rod"
    ABOD = "abod"
    SOS = "sos"
    LSCP = "lscp"
    SOD = "sod"
    VAE = "vae"
    PCA = "pca"
    MCD = "mcd"
    MODIFIED_ZSCORE = "modified_zscore"
    STL_GESD = "stl_gesd"
    SPECTRAL_RESIDUAL = "spectral_residual"
    CUSUM = "cusum"
    HAMPEL = "hampel"
    CHANGEPOINT = "changepoint"
    PEER_DIVERGENCE = "peer_divergence"
    PEER_PCA = "peer_pca"
    PEER_FUNCTIONAL_DEPTH = "peer_functional_depth"
    PEER_FEATURE_ISOLATION = "peer_feature_isolation"
    PEER_DTW_LOF = "peer_dtw_lof"
    PEER_MATRIX_PROFILE = "peer_matrix_profile"
    # Local forecast
    EXPONENTIAL_SMOOTHING = "exponential_smoothing"
    FFT = "fft"
    THETA = "theta"
    ARIMA = "arima"
    AUTO_ARIMA = "auto_arima"
    FOUR_THETA = "four_theta"
    NAIVE_MEAN = "naive_mean"
    NAIVE_SEASONAL = "naive_seasonal"
    NAIVE_DRIFT = "naive_drift"
    NAIVE_MOVING_AVG = "naive_moving_avg"
    CROSTON = "croston"
    PROPHET = "prophet"
    # Global forecast (sklearn-like)
    LINEAR_REGRESSION = "linear_regression"
    RANDOM_FOREST = "random_forest"
    LIGHTGBM = "lightgbm"
    XGBOOST = "xgboost"
    # Deep learning (torch)
    NBEATS = "nbeats"
    NHITS = "nhits"
    TFT = "tft"
    DLINEAR = "dlinear"
    NLINEAR = "nlinear"
    TCN = "tcn"
    TRANSFORMER = "transformer"
    BLOCK_RNN = "block_rnn"
    TIDE = "tide"
    TSMIXER = "tsmixer"
    # Foundation models (pre-trained, HuggingFace Hub)
    CHRONOS2 = "chronos2"
    TIMESFM = "timesfm"
    TSPULSE = "tspulse"
    # Deep learning scorers (GPU-accelerated)
    DEEP_SVDD = "deep_svdd"
    AUTOENCODER = "autoencoder"
    DAGMM = "dagmm"
    ANOMALY_TRANSFORMER = "anomaly_transformer"
    TRANAD = "tranad"
    # Foundation models (pre-trained, anomaly detection)
    MOMENT = "moment"
    LAG_LLAMA = "lag_llama"


class DetectorType(str, Enum):
    QUANTILE = "quantile"
    THRESHOLD = "threshold"
    IQR = "iqr"
